/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jambalaya_jni_Main */

#ifndef _Included_jambalaya_jni_Main
#define _Included_jambalaya_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jambalaya_jni_Main
 * Method:    calcNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jambalaya_jni_Main_calcNative__
  (JNIEnv *, jclass);

/*
 * Class:     jambalaya_jni_Main
 * Method:    calcNative
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_jambalaya_jni_Main_calcNative___3B
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
